source:
	sed -e "s/{{SZ}}/4/g" -e "s/{{SM}}/int32/g" -e "s/{{BG}}/Int32/g" template.go.tpl > ../int32.go
	sed -e "s/{{SZ}}/4/g" -e "s/{{SM}}/int32/g" -e "s/{{BG}}/Int32/g" template_test.go.tpl > ../int32_test.go
	sed -e "s/{{SZ}}/8/g" -e "s/{{SM}}/int64/g" -e "s/{{BG}}/Int64/g" template.go.tpl > ../int64.go
	sed -e "s/{{SZ}}/8/g" -e "s/{{SM}}/int64/g" -e "s/{{BG}}/Int64/g" template_test.go.tpl > ../int64_test.go
	sed -e "s/{{SZ}}/4/g" -e "s/{{SM}}/uint32/g" -e "s/{{BG}}/Uint32/g" template.go.tpl > ../uint32.go
	sed -e "s/{{SZ}}/4/g" -e "s/{{SM}}/uint32/g" -e "s/{{BG}}/Uint32/g" template_test.go.tpl > ../uint32_test.go
	sed -e "s/{{SZ}}/8/g" -e "s/{{SM}}/uint64/g" -e "s/{{BG}}/Uint64/g" template.go.tpl > ../uint64.go
	sed -e "s/{{SZ}}/8/g" -e "s/{{SM}}/uint64/g" -e "s/{{BG}}/Uint64/g" template_test.go.tpl > ../uint64_test.go
