// Code generated by protoc-gen-go.
// source: protocol.proto
// DO NOT EDIT!

/*
Package segfile is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	Metadata
*/
package segfile

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Metadata struct {
	// path to store files
	Path string `protobuf:"bytes,1,opt" json:"Path,omitempty"`
	// files will be prefixed with this string
	Prefix string `protobuf:"bytes,2,opt" json:"Prefix,omitempty"`
	// size of a segment file
	FileSize int64 `protobuf:"varint,3,opt" json:"FileSize,omitempty"`
	// available segment files
	Segments int64 `protobuf:"varint,4,opt" json:"Segments,omitempty"`
	// number of bytes used
	DataSize int64 `protobuf:"varint,5,opt" json:"DataSize,omitempty"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
